apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
    app: my-web-app
spec:
  selector:
    app: my-web-app
  type: NodePort               # Expose the service externally on a Node port
  ports:
    - protocol: TCP
      port: 80                 # Service port
      targetPort: 80           # Container port
      nodePort: 30008          # Exposed port on localhost (access via browser)
